### ISSUE TITLE
Missing scope for wallet error.

### ISSUE THREAD

**Issue by flemingho** [pi-apps/pi-python#5]
Hi there,

I am debugging through pi_python_test.py. I have entered my developer wallet_private_seed and API-key, but I am getting a "missing_scope" for "wallet_address" message.

![image](https://github.com/pi-apps/pi-python/assets/18223431/70a0b4e9-86b9-45fb-87d0-cecbd0afe6cb)

I'm wondering how to resolve this issue?

Thanks.

**Comment by flemingho** [comment]
I figured it out. I needed to authenticate my user account (in another app) that passes in "wallet_address" as one of the scopes, and confirm the prompt.

```
        // Authenticate the user, and get permission to request payments from them:
        const scopes = ['username', 'payments', 'wallet_address'];
...
        window.loginUser = async () => {
            let authUser = await Pi.authenticate(scopes, DoIncompletePaymentFound);
            return authUser;
        }
```

**Comment by rockcesar** [comment]
You're right @flemingho . Greetings!.

**Comment by rockcesar** [comment]
Done.

**Comment by flemingho** [comment]
I figured it out. I needed to authenticate my user account (in another app) that passes in "wallet_address" as one of the scopes, and confirm the prompt.

```
        // Authenticate the user, and get permission to request payments from them:
        const scopes = ['username', 'payments', 'wallet_address'];
...
        window.loginUser = async () => {
            let authUser = await Pi.authenticate(scopes, DoIncompletePaymentFound);
            return authUser;
        }
```
