### ISSUE TITLE
Passphrase problem!

### ISSUE THREAD

**Issue by vnhai328** [pi-apps/pi-python#8]
![image](https://github.com/user-attachments/assets/136c58b7-782d-4a9d-ab10-e818f7c14c47)
I want use passphrase to load account but it give to me another account

**Comment by rockcesar** [comment]
This happens because you need an special conversion from Mnemonic to Secret.

First use this one to get Secret from Mnemonic in NodeJS:

https://github.com/pi-apps/LatinChain/tree/main/Pi_A2U_payment/mnemonicToSecret

Then, use from_secret in my Python code.
